// <auto-generated />
using System;
using Gym.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260629225044_AddNewMemberEntity")]
    partial class AddNewMemberEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gym.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsManual")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Date");

                    b.HasIndex("MemberId", "Date");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.BackupLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BackupDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BackupDate");

                    b.ToTable("BackupLogs", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.DeviceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceLogs", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AdminSignature")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiseaseType")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FingerprintDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("FreeMonths")
                        .HasColumnType("int");

                    b.Property<int>("FreezeDays")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("HasDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MemberSignature")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferralSource")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubscriptionDurationMonths")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubscriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SubscriptionPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasFilter("[NationalId] IS NOT NULL");

                    b.HasIndex("PackageId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FreezeEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FreezeStartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<int>("RemainingVisits")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("MemberId", "Status");

                    b.ToTable("Memberships", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.MembershipPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int?>("FreezeDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxVisits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MembershipPlans", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPending")
                        .HasColumnType("bit");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("Status", "ScheduledDate");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Offers", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-ef56-789012345678"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(5122),
                            Description = "View members",
                            Name = "members.read"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-f678-901234567890"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7056),
                            Description = "Create/Edit members",
                            Name = "members.write"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-3456-a789-012345678901"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7061),
                            Description = "Delete members",
                            Name = "members.delete"
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4567-b890-123456789012"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7064),
                            Description = "View plans",
                            Name = "plans.read"
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-5678-c901-234567890123"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7077),
                            Description = "Create/Edit plans",
                            Name = "plans.write"
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-b4c5-6789-d012-345678901234"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7079),
                            Description = "View attendance",
                            Name = "attendance.read"
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-7890-e123-456789012345"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7080),
                            Description = "Record attendance",
                            Name = "attendance.write"
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-8901-f234-567890123456"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7082),
                            Description = "View payments",
                            Name = "payments.read"
                        },
                        new
                        {
                            Id = new Guid("a3b4c5d6-e7f8-9012-a345-678901234567"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7083),
                            Description = "Process payments",
                            Name = "payments.write"
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-f8a9-0123-b456-789012345678"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7084),
                            Description = "View reports",
                            Name = "reports.read"
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-a9b0-1234-c567-890123456789"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7085),
                            Description = "View settings",
                            Name = "settings.read"
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-b0c1-2345-d678-901234567890"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7087),
                            Description = "Manage settings",
                            Name = "settings.write"
                        },
                        new
                        {
                            Id = new Guid("e7f8a9b0-c1d2-3456-e789-012345678901"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7088),
                            Description = "Manage devices",
                            Name = "devices.manage"
                        },
                        new
                        {
                            Id = new Guid("f8a9b0c1-d2e3-4567-f890-123456789012"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7127),
                            Description = "Manage backups",
                            Name = "backup.manage"
                        },
                        new
                        {
                            Id = new Guid("a9b0c1d2-e3f4-5678-a901-234567890123"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7196),
                            Description = "Manage offers",
                            Name = "offers.manage"
                        },
                        new
                        {
                            Id = new Guid("d1e2f3a4-b5c6-7890-d123-456789012345"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 470, DateTimeKind.Utc).AddTicks(7198),
                            Description = "Manage users",
                            Name = "users.manage"
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 186, DateTimeKind.Utc).AddTicks(5414),
                            Description = "Full system access",
                            IsSystem = true,
                            Name = "Owner"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 186, DateTimeKind.Utc).AddTicks(6419),
                            Description = "Front desk operations",
                            IsSystem = true,
                            Name = "Receptionist"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 186, DateTimeKind.Utc).AddTicks(6421),
                            Description = "Trainer limited access",
                            IsSystem = true,
                            Name = "Trainer"
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("780f2da0-31ef-4559-9ffe-1262ed47389d"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("e5f6a7b8-c9d0-1234-ef56-789012345678"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("f847c126-7fc4-4a31-8198-a7c02bef0c7f"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("f6a7b8c9-d0e1-2345-f678-901234567890"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("355745ae-d2cf-411b-9b8b-63dec21c8af2"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("a7b8c9d0-e1f2-3456-a789-012345678901"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("7487240c-b9bb-491a-bc54-69fad79a1573"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("b8c9d0e1-f2a3-4567-b890-123456789012"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("ef2c129f-b76a-4d20-8b4b-462f4deabbbd"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("c9d0e1f2-a3b4-5678-c901-234567890123"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("8d84b051-ef2a-416a-828c-68bbf7cf5b24"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("d0e1f2a3-b4c5-6789-d012-345678901234"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("4a29139f-b306-47fb-8513-a2f1193ed0fd"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("e1f2a3b4-c5d6-7890-e123-456789012345"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("ac7822ca-3bbc-4669-9b6b-07e6f49d45fc"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("f2a3b4c5-d6e7-8901-f234-567890123456"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("59c0d8cb-b976-487f-a098-1330f6e9082a"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("a3b4c5d6-e7f8-9012-a345-678901234567"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("1900a968-b8f6-425d-89a3-09a344f32341"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("b4c5d6e7-f8a9-0123-b456-789012345678"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("ce9e7b1f-35c6-4c9e-b26e-c7e635ee0083"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("c5d6e7f8-a9b0-1234-c567-890123456789"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("b5f48274-e6d5-4d17-bd4b-aba6a020d9b4"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("d6e7f8a9-b0c1-2345-d678-901234567890"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("9dccbc0a-9798-4823-9626-88b35df580e6"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("e7f8a9b0-c1d2-3456-e789-012345678901"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("2c2fa57d-3700-46ef-baf5-a83b9deb47ce"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("f8a9b0c1-d2e3-4567-f890-123456789012"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("aed39055-9d59-4d6b-9811-6956e05bff29"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("a9b0c1d2-e3f4-5678-a901-234567890123"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("cfd7c3f6-1bc8-4e62-97fd-b2e60c64aa3d"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("d1e2f3a4-b5c6-7890-d123-456789012345"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("c72c22d3-d59c-4d46-9a1e-d12267783235"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("e5f6a7b8-c9d0-1234-ef56-789012345678"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901")
                        },
                        new
                        {
                            Id = new Guid("23681755-d602-4f32-8224-4a35999a165a"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("b8c9d0e1-f2a3-4567-b890-123456789012"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901")
                        },
                        new
                        {
                            Id = new Guid("a90c1bd8-05df-4c01-b0d2-014b3a11d8fd"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("d0e1f2a3-b4c5-6789-d012-345678901234"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901")
                        },
                        new
                        {
                            Id = new Guid("77864273-21ab-4fc7-8a3d-ef3afc51f912"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("e1f2a3b4-c5d6-7890-e123-456789012345"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901")
                        },
                        new
                        {
                            Id = new Guid("f3d21642-78ec-4ee7-9b2c-4b9893a99ac0"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("f2a3b4c5-d6e7-8901-f234-567890123456"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901")
                        },
                        new
                        {
                            Id = new Guid("41c5b2c9-2871-4cc4-af57-c5b2991598f4"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("a3b4c5d6-e7f8-9012-a345-678901234567"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901")
                        },
                        new
                        {
                            Id = new Guid("320fd0c2-d4fb-40de-b0d1-4b3ae4051ed6"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("e5f6a7b8-c9d0-1234-ef56-789012345678"),
                            RoleId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012")
                        },
                        new
                        {
                            Id = new Guid("23b4e224-9e35-4e8c-ae2a-20e550f9f839"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("d0e1f2a3-b4c5-6789-d012-345678901234"),
                            RoleId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012")
                        },
                        new
                        {
                            Id = new Guid("4a366db1-b3f1-43ed-898f-2ea474eaf709"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 472, DateTimeKind.Utc).AddTicks(953),
                            PermissionId = new Guid("b4c5d6e7-f8a9-0123-b456-789012345678"),
                            RoleId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012")
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0c1d2e3-f4a5-6789-b012-345678901234"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 473, DateTimeKind.Utc).AddTicks(3349),
                            Description = "Gym display name",
                            Group = "General",
                            IsEncrypted = false,
                            Key = "GymName",
                            Value = "My Gym"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-7890-c123-456789012345"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 473, DateTimeKind.Utc).AddTicks(3349),
                            Description = "ZKTeco MB2000 IP address",
                            Group = "Device",
                            IsEncrypted = false,
                            Key = "DeviceIP",
                            Value = "192.168.1.201"
                        },
                        new
                        {
                            Id = new Guid("d2e3f4a5-b6c7-8901-d234-567890123456"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 473, DateTimeKind.Utc).AddTicks(3349),
                            Description = "ZKTeco MB2000 port",
                            Group = "Device",
                            IsEncrypted = false,
                            Key = "DevicePort",
                            Value = "4370"
                        },
                        new
                        {
                            Id = new Guid("e3f4a5b6-c7d8-9012-e345-678901234567"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 473, DateTimeKind.Utc).AddTicks(3349),
                            Description = "Database backup location",
                            Group = "Backup",
                            IsEncrypted = false,
                            Key = "BackupPath",
                            Value = "C:\\Backups\\GymManagement"
                        },
                        new
                        {
                            Id = new Guid("f4a5b6c7-d8e9-0123-f456-789012345678"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 473, DateTimeKind.Utc).AddTicks(3349),
                            Description = "Gym opening time",
                            Group = "General",
                            IsEncrypted = false,
                            Key = "WorkingHoursStart",
                            Value = "08:00"
                        },
                        new
                        {
                            Id = new Guid("a5b6c7d8-e9f0-1234-a567-890123456789"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 473, DateTimeKind.Utc).AddTicks(3349),
                            Description = "Gym closing time",
                            Group = "General",
                            IsEncrypted = false,
                            Key = "WorkingHoursEnd",
                            Value = "22:00"
                        },
                        new
                        {
                            Id = new Guid("b6c7d8e9-f0a1-2345-b678-901234567890"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 473, DateTimeKind.Utc).AddTicks(3349),
                            Description = "Membership expiry reminder days",
                            Group = "Notifications",
                            IsEncrypted = false,
                            Key = "ReminderDays",
                            Value = "7,3,1"
                        },
                        new
                        {
                            Id = new Guid("c7d8e9f0-a1b2-3456-c789-012345678901"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 473, DateTimeKind.Utc).AddTicks(3349),
                            Description = "Enable WhatsApp notifications",
                            Group = "Notifications",
                            IsEncrypted = false,
                            Key = "WhatsAppEnabled",
                            Value = "false"
                        },
                        new
                        {
                            Id = new Guid("d8e9f0a1-b2c3-4567-d890-123456789012"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 473, DateTimeKind.Utc).AddTicks(3349),
                            Description = "Enable SMS notifications",
                            Group = "Notifications",
                            IsEncrypted = false,
                            Key = "SMSEnabled",
                            Value = "false"
                        },
                        new
                        {
                            Id = new Guid("e9f0a1b2-c3d4-5678-e901-234567890123"),
                            CreatedAt = new DateTime(2026, 6, 29, 22, 50, 43, 473, DateTimeKind.Utc).AddTicks(3349),
                            Description = "Default currency symbol",
                            Group = "General",
                            IsEncrypted = false,
                            Key = "DefaultCurrency",
                            Value = "EGP"
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-def4-567890123456"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gym.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$Skgb0mL5DIF3N88WtHaCpeyyeK2k7TRfKtr2uc4qF7l5QfvpuvJ6G",
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Device", "Device")
                        .WithMany("Attendances")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gym.Domain.Entities.Member", "Member")
                        .WithMany("Attendances")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Gym.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Gym.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gym.Domain.Entities.DeviceLog", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Device", "Device")
                        .WithMany("DeviceLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Member", b =>
                {
                    b.HasOne("Gym.Domain.Entities.MembershipPlan", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Membership", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gym.Domain.Entities.MembershipPlan", "Plan")
                        .WithMany("Memberships")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Member", "Member")
                        .WithMany("Notifications")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Gym.Domain.Entities.User", "Employee")
                        .WithMany("Payments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gym.Domain.Entities.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Gym.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Gym.Domain.Entities.User", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Device", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("DeviceLogs");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Member", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Memberships");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Gym.Domain.Entities.MembershipPlan", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Gym.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
