// <auto-generated />
using System;
using Gym.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym.Infrastructure.Migrations
{
    [DbContext(typeof(GymDbContext))]
    partial class GymDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gym.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsManual")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Date");

                    b.HasIndex("MemberId", "Date");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.BackupLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BackupDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BackupDate");

                    b.ToTable("BackupLogs", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.DeviceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceLogs", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AdminSignature")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiseaseType")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("FingerprintDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("FreeMonths")
                        .HasColumnType("int");

                    b.Property<int>("FreezeDays")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("HasDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MemberSignature")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferralSource")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubscriptionDurationMonths")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubscriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SubscriptionPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PackageId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FreezeEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FreezeStartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<int>("RemainingVisits")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("MemberId", "Status");

                    b.ToTable("Memberships", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.MembershipPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int?>("FreezeDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxVisits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MembershipPlans", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPending")
                        .HasColumnType("bit");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("Status", "ScheduledDate");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Offers", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<int?>("FreePeriodMonths")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxFreezeDays")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Packages", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-ef56-789012345678"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(2945),
                            Description = "View members",
                            Name = "members.read"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-f678-901234567890"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4020),
                            Description = "Create/Edit members",
                            Name = "members.write"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-3456-a789-012345678901"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4022),
                            Description = "Delete members",
                            Name = "members.delete"
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4567-b890-123456789012"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4023),
                            Description = "View plans",
                            Name = "plans.read"
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-5678-c901-234567890123"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4024),
                            Description = "Create/Edit plans",
                            Name = "plans.write"
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-b4c5-6789-d012-345678901234"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4025),
                            Description = "View attendance",
                            Name = "attendance.read"
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-7890-e123-456789012345"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4025),
                            Description = "Record attendance",
                            Name = "attendance.write"
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-8901-f234-567890123456"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4026),
                            Description = "View payments",
                            Name = "payments.read"
                        },
                        new
                        {
                            Id = new Guid("a3b4c5d6-e7f8-9012-a345-678901234567"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4027),
                            Description = "Process payments",
                            Name = "payments.write"
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-f8a9-0123-b456-789012345678"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4028),
                            Description = "View reports",
                            Name = "reports.read"
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-a9b0-1234-c567-890123456789"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4029),
                            Description = "View settings",
                            Name = "settings.read"
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-b0c1-2345-d678-901234567890"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4030),
                            Description = "Manage settings",
                            Name = "settings.write"
                        },
                        new
                        {
                            Id = new Guid("e7f8a9b0-c1d2-3456-e789-012345678901"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4031),
                            Description = "Manage devices",
                            Name = "devices.manage"
                        },
                        new
                        {
                            Id = new Guid("f8a9b0c1-d2e3-4567-f890-123456789012"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4045),
                            Description = "Manage backups",
                            Name = "backup.manage"
                        },
                        new
                        {
                            Id = new Guid("a9b0c1d2-e3f4-5678-a901-234567890123"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4046),
                            Description = "Manage offers",
                            Name = "offers.manage"
                        },
                        new
                        {
                            Id = new Guid("d1e2f3a4-b5c6-7890-d123-456789012345"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 720, DateTimeKind.Utc).AddTicks(4046),
                            Description = "Manage users",
                            Name = "users.manage"
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 494, DateTimeKind.Utc).AddTicks(2667),
                            Description = "Full system access",
                            IsSystem = true,
                            Name = "Owner"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 494, DateTimeKind.Utc).AddTicks(3713),
                            Description = "Front desk operations",
                            IsSystem = true,
                            Name = "Receptionist"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 494, DateTimeKind.Utc).AddTicks(3714),
                            Description = "Trainer limited access",
                            IsSystem = true,
                            Name = "Trainer"
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7dc649b3-0e4d-a02d-25b2-1533c6da1485"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("e5f6a7b8-c9d0-1234-ef56-789012345678"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("c01cc128-784d-f6dd-8543-496e731fa31a"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("f6a7b8c9-d0e1-2345-f678-901234567890"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("7d73a719-0bf4-f70e-384e-ef6a71bdc88f"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("a7b8c9d0-e1f2-3456-a789-012345678901"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("be8fe1d9-d5f7-fc0d-1c62-f23ec408ee0d"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("b8c9d0e1-f2a3-4567-b890-123456789012"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("94e3232d-330d-080b-3968-8c0b0422abd3"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("c9d0e1f2-a3b4-5678-c901-234567890123"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("97577489-44d4-9fca-3e5a-a7ff99c25f60"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("d0e1f2a3-b4c5-6789-d012-345678901234"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("fb0338fb-fc95-ac51-0a37-7cc90b17ec50"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("e1f2a3b4-c5d6-7890-e123-456789012345"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("95403e61-b5ef-2b2e-e6db-cb2875fdd651"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("f2a3b4c5-d6e7-8901-f234-567890123456"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("411c0941-f12c-e117-e542-7561547fae68"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("a3b4c5d6-e7f8-9012-a345-678901234567"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("38e68501-6aa4-2723-251e-83ab85145eda"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("b4c5d6e7-f8a9-0123-b456-789012345678"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("faed05e8-a7e0-30e1-7f2f-3f59a113fd18"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("c5d6e7f8-a9b0-1234-c567-890123456789"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("f6d95421-adde-78dc-a3e8-ada50506e534"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("d6e7f8a9-b0c1-2345-d678-901234567890"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("1a447bea-0884-a7b8-5c95-9aa22876b650"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("e7f8a9b0-c1d2-3456-e789-012345678901"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("ce45517e-5f0e-7330-9534-bae4dcee4905"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("f8a9b0c1-d2e3-4567-f890-123456789012"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("d487e031-bfa2-73dc-4031-273dbfae68c5"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("a9b0c1d2-e3f4-5678-a901-234567890123"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("18ca3a8f-4030-37b6-bb6c-51d7f78326bf"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("d1e2f3a4-b5c6-7890-d123-456789012345"),
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("578d3c75-7400-e248-983f-cb4d4f13fdd3"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("e5f6a7b8-c9d0-1234-ef56-789012345678"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901")
                        },
                        new
                        {
                            Id = new Guid("37fafc7e-cec4-f1e7-0639-0769adc78e8c"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("b8c9d0e1-f2a3-4567-b890-123456789012"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901")
                        },
                        new
                        {
                            Id = new Guid("dde6c68e-c7ec-19c2-65a8-d1c9abf4dbd1"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("d0e1f2a3-b4c5-6789-d012-345678901234"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901")
                        },
                        new
                        {
                            Id = new Guid("7b9944e2-4c52-0d53-1edd-ccd1d7316518"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("e1f2a3b4-c5d6-7890-e123-456789012345"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901")
                        },
                        new
                        {
                            Id = new Guid("0cd25d71-346b-3908-42cf-d84115ab6e8b"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("f2a3b4c5-d6e7-8901-f234-567890123456"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901")
                        },
                        new
                        {
                            Id = new Guid("618876f6-daa1-fc83-c047-480bf88c794e"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("a3b4c5d6-e7f8-9012-a345-678901234567"),
                            RoleId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901")
                        },
                        new
                        {
                            Id = new Guid("c4522deb-c1b9-9234-005e-bdb3b1c5d30b"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("e5f6a7b8-c9d0-1234-ef56-789012345678"),
                            RoleId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012")
                        },
                        new
                        {
                            Id = new Guid("12205256-ff83-d1a7-ca36-ef013e4348dd"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("d0e1f2a3-b4c5-6789-d012-345678901234"),
                            RoleId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012")
                        },
                        new
                        {
                            Id = new Guid("df7c114a-08b2-ca57-d10a-9458a9126cc7"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 721, DateTimeKind.Utc).AddTicks(1835),
                            PermissionId = new Guid("b4c5d6e7-f8a9-0123-b456-789012345678"),
                            RoleId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012")
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0c1d2e3-f4a5-6789-b012-345678901234"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 723, DateTimeKind.Utc).AddTicks(153),
                            Description = "Gym display name",
                            Group = "General",
                            IsEncrypted = false,
                            Key = "GymName",
                            Value = "My Gym"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-7890-c123-456789012345"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 723, DateTimeKind.Utc).AddTicks(153),
                            Description = "ZKTeco MB2000 IP address",
                            Group = "Device",
                            IsEncrypted = false,
                            Key = "DeviceIP",
                            Value = "192.168.1.201"
                        },
                        new
                        {
                            Id = new Guid("d2e3f4a5-b6c7-8901-d234-567890123456"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 723, DateTimeKind.Utc).AddTicks(153),
                            Description = "ZKTeco MB2000 port",
                            Group = "Device",
                            IsEncrypted = false,
                            Key = "DevicePort",
                            Value = "4370"
                        },
                        new
                        {
                            Id = new Guid("e3f4a5b6-c7d8-9012-e345-678901234567"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 723, DateTimeKind.Utc).AddTicks(153),
                            Description = "Database backup location",
                            Group = "Backup",
                            IsEncrypted = false,
                            Key = "BackupPath",
                            Value = "C:\\Backups\\GymManagement"
                        },
                        new
                        {
                            Id = new Guid("f4a5b6c7-d8e9-0123-f456-789012345678"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 723, DateTimeKind.Utc).AddTicks(153),
                            Description = "Gym opening time",
                            Group = "General",
                            IsEncrypted = false,
                            Key = "WorkingHoursStart",
                            Value = "08:00"
                        },
                        new
                        {
                            Id = new Guid("a5b6c7d8-e9f0-1234-a567-890123456789"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 723, DateTimeKind.Utc).AddTicks(153),
                            Description = "Gym closing time",
                            Group = "General",
                            IsEncrypted = false,
                            Key = "WorkingHoursEnd",
                            Value = "22:00"
                        },
                        new
                        {
                            Id = new Guid("b6c7d8e9-f0a1-2345-b678-901234567890"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 723, DateTimeKind.Utc).AddTicks(153),
                            Description = "Membership expiry reminder days",
                            Group = "Notifications",
                            IsEncrypted = false,
                            Key = "ReminderDays",
                            Value = "7,3,1"
                        },
                        new
                        {
                            Id = new Guid("c7d8e9f0-a1b2-3456-c789-012345678901"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 723, DateTimeKind.Utc).AddTicks(153),
                            Description = "Enable WhatsApp notifications",
                            Group = "Notifications",
                            IsEncrypted = false,
                            Key = "WhatsAppEnabled",
                            Value = "false"
                        },
                        new
                        {
                            Id = new Guid("d8e9f0a1-b2c3-4567-d890-123456789012"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 723, DateTimeKind.Utc).AddTicks(153),
                            Description = "Enable SMS notifications",
                            Group = "Notifications",
                            IsEncrypted = false,
                            Key = "SMSEnabled",
                            Value = "false"
                        },
                        new
                        {
                            Id = new Guid("e9f0a1b2-c3d4-5678-e901-234567890123"),
                            CreatedAt = new DateTime(2026, 6, 30, 1, 30, 4, 723, DateTimeKind.Utc).AddTicks(153),
                            Description = "Default currency symbol",
                            Group = "General",
                            IsEncrypted = false,
                            Key = "DefaultCurrency",
                            Value = "EGP"
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-def4-567890123456"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gym.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$Uuso/x/mhWPcVrNHqin8ru1lvWqNiEXRC9FBNoN4GM9MuJSvZPpUm",
                            RoleId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Device", "Device")
                        .WithMany("Attendances")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gym.Domain.Entities.Member", "Member")
                        .WithMany("Attendances")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Gym.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Gym.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gym.Domain.Entities.DeviceLog", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Device", "Device")
                        .WithMany("DeviceLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Member", b =>
                {
                    b.HasOne("Gym.Domain.Entities.MembershipPlan", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Membership", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gym.Domain.Entities.MembershipPlan", "Plan")
                        .WithMany("Memberships")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Member", "Member")
                        .WithMany("Notifications")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Gym.Domain.Entities.User", "Employee")
                        .WithMany("Payments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gym.Domain.Entities.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Gym.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Gym.Domain.Entities.User", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Device", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("DeviceLogs");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Member", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Memberships");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Gym.Domain.Entities.MembershipPlan", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Gym.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
